### ISSUE TITLE
Clarification around when using Filestorage from Power VS

### ISSUE THREAD

**Issue by ibmchas** [ibm-cloud-docs/FileStorage#9]
I miss some clarification in the documentation when it comes to the Power VS's services as this requires a GRE tunnel in order to connect to those native services which is only exposed as Private Endpoints, FileStorage being one of them. It would properly be good to enlighten the reader about the such limitation.

The be 9000 all over as designed is fine but when you then need configure advertisements and setup a GRE tunnel from one cloud service (Power VS) to connect to another (File Storage) it should be properly be added as a Service Notice as you can't get 9000 over GRE -  optimal setting MTU for FileStorage would be MTU of 1476 when using GRE.

**Comment by vickmuir** [comment]
I assume this is feedback to our Enabling Jumbo Frames topic. We do indeed recommend that all devices that the Storage traffic is passing through are set to the same 9,000 MTU value. Classic File Storage is designed to be on the same VLAN as the server that is accessing it without any physical or virtual firewalls between them. 
I am not familiar with the Power Systems Virtual Server offering, but since you need Direct Link to connect to the IBM Cloud network I believe the setup is different than our classic VSIs. Direct Link Dedicated and Direct Link Dedicated Hosting both support Jumbo Frames. However, even though it could support it theoretically, Direct Link Connect is set up with 1500-byte MTU support. That's the reason for the MTU mismatch.
I am not sure what the correct way is to mount Classic File Storage volumes on a Power VS and if it is even supported. The Power Systems VS documentation only lists IBM Cloud Bare Metal Servers, Kubernetes containers, and Cloud Object Storage as available IBM Cloud resources. However, their documentation also states that over the next few months, the Power Systems Virtual Server service plans to continue to evolve its network connectivity capabilities through further automation and integration. From the File Storage side, I can not confirm that access to our service is going to be included.
I have contacted the Information Developer who maintains the IBM Power Systems Virtual Server documentation with a request to update their topics with more information about available storage options. I'm sorry I could not be of more help. I hope you have a nice day.
